stages:
  - build
  - test
  - deploy

.variables_template: &variables_definition
  variables:
    BASE_NAME: "chimaerad"
    PKG_CONFIG_PATH: "/opt/lv2/lib/pkgconfig:/opt/${CI_BUILD_NAME}/lib/pkgconfig"
    TOOLCHAIN_FILE: "${CI_PROJECT_DIR}/cmake/${CI_BUILD_NAME}.cmake"

.common_template: &common_definition
  <<: *variables_definition
  stage: build
  artifacts:
    name: "${CI_BUILD_NAME}-${BASE_NAME}-${CI_BUILD_REF_NAME}-${CI_BUILD_REF}"
    paths:
      - "${BASE_NAME}-${CI_BUILD_REF_NAME}-${CI_BUILD_REF}/"

.build_template: &build_definition
  <<: *common_definition
  before_script:
    - apt-get install -y -q zip libavahi-compat-libdnssd-dev
  script:
    - mkdir -p ${BASE_NAME}-${CI_BUILD_REF_NAME}-${CI_BUILD_REF}/${CI_BUILD_NAME}
    - mkdir build
    - pushd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE} ..
    - cmake .. # needed for darwin
    - make
    - make install
    - cp /usr/local/bin/chimaerad ../${BASE_NAME}-${CI_BUILD_REF_NAME}-${CI_BUILD_REF}/${CI_BUILD_NAME}/.
    - cp /usr/local/bin/chimaerad.app ../${BASE_NAME}-${CI_BUILD_REF_NAME}-${CI_BUILD_REF}/${CI_BUILD_NAME}/.
    - cp /usr/local/share/chimaerad/app.zip ../${BASE_NAME}-${CI_BUILD_REF_NAME}-${CI_BUILD_REF}/${CI_BUILD_NAME}/.

.universal_linux_template: &universal_linux_definition
  image: ventosus/universal-linux-gnu
  <<: *build_definition

.arm_linux_template: &arm_linux_definition
  image: ventosus/arm-linux-gnueabihf
  <<: *build_definition

.universal_w64_template: &universal_w64_definition
  image: ventosus/universal-w64-mingw32
  <<: *build_definition

.universal_apple_template: &universal_apple_definition
  image: ventosus/universal-apple-darwin
  <<: *build_definition

# building in docker
x86_64-linux-gnu:
  <<: *universal_linux_definition

#i686-linux-gnu:
#  <<: *universal_linux_definition

#arm-linux-gnueabihf:
#  <<: *arm_linux_definition

#x86_64-w64-mingw32:
#  <<: *universal_w64_definition

#i686-w64-mingw32:
#  <<: *universal_w64_definition

universal-apple-darwin:
  <<: *universal_apple_definition

pack:
  <<: *variables_definition
  stage: deploy
  script:
    - echo 'packing up...'
  artifacts:
    name: "${BASE_NAME}-${CI_BUILD_REF_NAME}-${CI_BUILD_REF}"
    paths:
      - "${BASE_NAME}-${CI_BUILD_REF_NAME}-${CI_BUILD_REF}"
