language:
 - c
os:
 - linux
compiler:
 - gcc
 - clang
before_install:
 - wget https://github.com/joyent/libuv/archive/v1.0.0.tar.gz
 - tar xzf v1.0.0.tar.gz
 - sudo add-apt-repository -y ppa:andykimpe/cmake
 - sudo apt-get -q update
 - sudo apt-get install cmake=2.8.12.2-3 
install:
 - pushd libuv-1.0.0 && sh autogen.sh && ./configure --prefix=/usr && make && sudo make install && popd
 - sudo apt-get install -y libjack-dev libasound2-dev libluajit-5.1-dev libzip-dev zip
before_script:
 - mkdir build && pushd build && cmake -DCMAKE_C_FLAGS="-std=gnu99" -DUSE_SYSTEM_RTMIDI=0 -DUSE_LUAJIT=1  .. && popd
script:
 - pushd build && make && sudo make install && popd
