language:
 - c
os:
 - linux
 - osx
compiler:
 - gcc
 - clang
before_install:
 - ifmac () { if [[ $TRAVIS_OS_NAME == osx ]]; then eval $@; fi; }
 - iflin () { if [[ $TRAVIS_OS_NAME == linux ]]; then eval $@; fi; }
 - ifmac brew update
 - iflin wget https://github.com/libuv/libuv/archive/v1.2.0.tar.gz
 - iflin tar xzf v1.2.0.tar.gz
 - iflin sudo add-apt-repository -y ppa:andykimpe/cmake
 - iflin sudo apt-get -q update
 - iflin sudo apt-get install cmake=2.8.12.2-3 
install:
 - ifmac brew install jack luajit lua libzip libuv
 - iflin pushd libuv-1.2.0 && iflin sh autogen.sh && iflin ./configure --prefix=/usr && iflin make && iflin sudo make install && iflin popd
 - iflin sudo apt-get install -y libjack-dev libasound2-dev libluajit-5.1-dev libzip-dev zip
before_script:
 - mkdir build && pushd build
 - ifmac cmake -DCMAKE_C_FLAGS="-std=gnu99" -DUSE_SYSTEM_RTMIDI=0 -DUSE_LUAJIT=1 -DUSE_JACK=0 ..
 - iflin cmake -DCMAKE_C_FLAGS="-std=gnu99" -DUSE_SYSTEM_RTMIDI=0 -DUSE_LUAJIT=1 -DUSE_JACK=1 ..
 - popd
script:
 - pushd build && make && sudo make install && popd
