language:
 - c
os:
 - linux
 - osx
compiler:
 - gcc
 - clang
before_install:
 - ifmac () { if [[ $TRAVIS_OS_NAME == osx ]]; then eval $@; fi; }
 - iflin () { if [[ $TRAVIS_OS_NAME == linux ]]; then eval $@; fi; }
 - iflingcc () { if [[ $TRAVIS_OS_NAME == linux && "$CC" == "gcc" ]]; then eval $@; fi; }
 - iflinclang () { if [[ $TRAVIS_OS_NAME == linux && "$CC" == "clang" ]]; then eval $@; fi; }
 - ifmac brew update
 - iflin wget https://github.com/libuv/libuv/archive/v1.7.5.tar.gz
 - iflin tar xzf v1.7.5.tar.gz
 - iflin sudo add-apt-repository -y ppa:andykimpe/cmake
 - iflinclang sudo add-apt-repository -y ppa:h-rayflood/llvm-upper
 - iflin sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - iflin sudo apt-get update -qq
install:
 - iflin sudo apt-get install cmake=2.8.12.2-3 libavahi-compat-libdnssd-dev
 - iflinclang sudo apt-get install -y clang-3.6 libstdc++-5-dev
 - iflingcc sudo apt-get install -y gcc-5 g++-5
 - ifmac brew install lua libzip libuv
 - iflin pushd libuv-1.7.5 && iflin sh autogen.sh && iflin ./configure --prefix=/usr && iflin make && iflin sudo make install && iflin popd
 - iflin sudo apt-get install -y liblua5.2-dev libzip-dev zip
before_script:
 - iflinclang export CXX="clang++-3.6" CC="clang-3.6" CFLAGS="-ffreestanding"
 - iflingcc export CXX="g++-5" CC="gcc-5"
 - mkdir build && pushd build
 - ifmac cmake ..
 - iflin cmake ..
 - popd
script:
 - pushd build && make && sudo make install && popd
