language:
 - c
os:
 - linux
 - osx
compiler:
 - gcc
 - clang
before_install:
 - ifmac () { if [[ $TRAVIS_OS_NAME == osx ]]; then eval $@; fi; }
 - iflin () { if [[ $TRAVIS_OS_NAME == linux ]]; then eval $@; fi; }
 - ifmac brew update
 - iflin wget https://github.com/libuv/libuv/archive/v1.7.5.tar.gz
 - iflin tar xzf v1.7.5.tar.gz
 - iflin sudo add-apt-repository -y ppa:andykimpe/cmake
 - iflin sudo apt-get -q update
 - iflin sudo apt-get install cmake=2.8.12.2-3 libavahi-compat-libdnssd-dev
install:
 - ifmac brew install lua libzip libuv
 - iflin pushd libuv-1.7.5 && iflin sh autogen.sh && iflin ./configure --prefix=/usr && iflin make && iflin sudo make install && iflin popd
 - iflin sudo apt-get install -y liblua-dev libzip-dev zip
before_script:
 - mkdir build && pushd build
 - ifmac cmake ..
 - iflin cmake ..
 - popd
script:
 - pushd build && make && sudo make install && popd
